server:
  port: 8080
  servlet:
    session:
      timeout: -1

spring:
  application:
    name: chatapp

broker:
  relay:
    host: ${activemq.host:localhost}
    user: admin
    password: admin

logging:
  level:
    org.springframework.messaging: trace

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    preferIpAddress: true
#    ipAddress: 127.0.0.1

ndp:
  security:
    clientId: http://csasit.ad.btk.bg
  rs:
    endpoint:
      rs714: http://esbppr2srv.drcenter.btk.bg:8280/services/WS_714_AutorizationMangement/authorize
