version: '3'

services:
  eureka-server:
    build: ./eureka
    image: pmitseas/eureka:1
    ports:
      - "8761:8761"
  gateway-server:
    build: ./gateway-server
    image: pmitseas/gateway:1
    environment:
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8761
    depends_on:
      - eureka-server
  chat-app:
    build: ./chatapp
    image: pmitseas/chat-app:1
    environment:
      - ACTIVEMQ_HOST=activemq
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8761
  activemq:
    image: vromero/activemq-artemis
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=admin
      - BROKER_CONFIG_CONNECTION_TTL=-1
    ports:
      - "8161:8161"
      - "61613:61613"
      - "61616:61616"
  nginx:
    build: ./nginx
    image: pmitseas/nginx:1
    volumes:
      - ./nginx/nginx.template:/etc/nginx/conf.d/nginx.template
    ports:
      - "8080:8080"
      - "443:443"
    environment:
      - GATEWAY=gateway-server
    depends_on:
      - gateway-server
    command: /bin/bash -c "envsubst '$$GATEWAY' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"