version: '3'

services:
  chat-app:
    build: .
    image: pmitseas/chat-app:1
    ports:
      - "8000:8000"
    environment:
      - ACTIVEMQ_HOST=activemq

  activemq:
    image: rabbitmq
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - "61616:61616"
      - "61613:61613"
      - "8161:8161"